### ISSUE TITLE
Fingerprinting in Style: Detecting Browser Extensions via Injected Style Sheets

### ISSUE THREAD

**Issue by franzs97** [prescience-data/dark-knowledge#1]
I thought this might be useful:
https://www.usenix.org/system/files/sec21-laperdrix.pdf

Year: 2021
Title: Fingerprinting in Style: Detecting Browser Extensions via Injected Style Sheets
Topics: Extensions
Authors: Pierre Laperdrix, Oleksii Starov, Quan Chen, Alexandros Kapravelos, Nick Nikiforakis

**Comment by prescience-data** [comment]
Added in https://github.com/prescience-data/dark-knowledge/commit/0908a71cf0c6a3473c2b312d2831baccb30b853d
